services:
  api:
    build: .
    container_name: voluntr-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: voluntr-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongo-data:
